# Generated by Django 5.2.5 on 2025-08-31 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_asset_component_consumable_item_journalentry_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pay_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.party'),
        ),
    ]
