# Generated by Django 5.2.5 on 2025-08-31 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_check_pay_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='as_of',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
