# Generated by Django 5.2.5 on 2025-08-31 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_check_pay_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], default='withdrawal', max_length=50),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.party'),
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='accounting.account')),
            ],
        ),
    ]
