# Generated by Django 5.2.5 on 2025-08-31 09:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderreturn',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesorderreturn',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 31, 9, 22, 54, 588010, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='channel',
            field=models.CharField(blank=True, default='MANUAL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.party'),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='mapping_status',
            field=models.CharField(choices=[('not_mapped', 'Not Mapped'), ('mapped', 'Mapped')], default='not_mapped', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('multi_payment', 'Multi Payment'), ('refund', 'Refund')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('refunded', 'Refunded'), ('pending', 'Pending'), ('processing', 'Processing')], default='finished', max_length=50),
        ),
    ]
