# Generated by Django 5.2.5 on 2025-08-31 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_salesorderreturn_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderreturn',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesorderreturn',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='accounting.party'),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='mapping_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorderreturn',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
