# Generated by Django 5.0.7 on 2025-09-02 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_salesorderreturn_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconcileStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beginning_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ending_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("ending_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "cleared_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconcileTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("cheque_expense", "Cheque Expense"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_cleared", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.account",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.party",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.reconcilestatement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reconciled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("discrepancy", "Has Discrepancy"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "statement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation",
                        to="accounting.reconcilestatement",
                    ),
                ),
            ],
        ),
    ]
