# Generated by Django 5.0.7 on 2025-09-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_reconcilestatement_reconciletransaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reconcilestatement",
            name="cleared_balance",
        ),
    ]
